/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: [
    {
        type: 'doc',
        label: 'Blade 3 Getting Started',
        id: 'blade-3-introduction',
    },
   {
      type: 'category',
      label: 'Mixtile Blade 3',
      link: {type: 'doc', id: 'index'},
      items : [
            {
                type: 'category',
                label: 'Quick Start Guide',
                items: [
                    'blade-3-quick-start-guide',
                    'blade-3-quick-start-guide.zh-cn',
                ]
            },
            {
                type: 'category',
                label: 'Serial Debugging',
                items: [
                    'blade-3-serial-debugging',
                    'blade-3-serial-debugging.zh-cn',
                ]
               ]
};

module.exports = sidebars;
